name: docker_publish

on:
  push:
    branches:
    - 'hiep/update-pipeline-version'
    tags:
    - '*'

jobs:
  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@hiep/add-platform
    # needs: ["lint_test"]
    secrets: inherit
    with:
      publish: true
      dockerfile: ./contrib/images/babylond/Dockerfile
      repoName: babylond
